jobs:
- deployment: VMDeploy
  displayName: web
  pool:
    vmImage: 'Ubuntu-18.04'
  environment:
    name: Virtual machine resource
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - script: sudo touch /home/azureuser/ss.txt